if ("${BUILD_CONFIG_DIR}" STREQUAL "")
message(STATUS "use default thirdparty config dir")
    set(BUILD_CONFIG_DIR ${PROJECT_SOURCE_DIR}/../thirdparty)
endif()

message(STATUS "BUILD_CONFIG_DIR is ${BUILD_CONFIG_DIR}")

list(APPEND CMAKE_MODULE_PATH ${BUILD_CONFIG_DIR}/thirdparty/cmake)
list(APPEND CMAKE_MODULE_PATH ${BUILD_CONFIG_DIR}/yuanrong/cmake)

include(observability_metrics)
include(litebus)
include(logs)
IF ("${FUNCTION_SYSTEM_BUILD_PART}" STREQUAL "ALL")
    include(datasystem)
ELSEIF ("${DATASYSTEM_RELY_ON}" STREQUAL "ON")
    include(datasystem)
endif ()

include(third_utils)
include(securec)
include(openssl)
include(zlib)
include(protobuf)
include(grpc)
include(etcd)
include(spdlog)
include(yaml)
include(cjson)
include(jemalloc)

if (BUILD_LLT)
    include(gtest_1_10_0)
endif()

set(litebus_ALL_LIB ${litebus_LIB} ${securec_LIB} ${yrlogs_LIB} pthread)